# Продакшн: JSON-логирование, БД из окружения
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  # Включаем под-профиль "json" для structured (JSON) логирования
  profiles:
    include: json

logging:
  level:
    root: INFO
    com.conditionservice: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: never