# Локальная разработка (профиль по умолчанию)
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/condition_service
    username: cs_user
    password: ${DB_PASSWORD:cs_user}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"